Add files via upload
Gaussiandra/Algorithms4SemMIPT pull request #1
Opened 2023-03-28 13:26 UTC by Gaussiandra

2023-04-09 02:21 UTC, RickMortey requested changes

2023-04-09 02:21 UTC, RickMortey commented on M.cpp
> +    std::vector<int> p(n);
Неочевидные без условия задачи имена переменных

2023-04-09 02:21 UTC, RickMortey commented on I.cpp
> +}
Где хэши?

2023-04-09 02:21 UTC, RickMortey commented on A.cpp
> +  std::vector<int> pi(n);
Неочевидные без условия задачи имена переменных

2023-04-09 02:21 UTC, RickMortey commented on I.cpp
> +}
С неймингом тоже беды есть

2023-04-09 02:21 UTC, RickMortey commented on A.cpp
> +  std::string p;
string and prefix, not p и s.
На будущее: любой нейминг в 1 символ, кроме итераторов (и то, если контекст понятен) -- бан.

2023-04-09 02:21 UTC, RickMortey commented on M.cpp
> +            c[u] = n_classes, p[sort_counter++] = u;
comma operator очень редко используется, читать трудно. В проде лучше написать пару лишних строчек. Давай представим что этот код пойдёт в прод и напишем пару лишних строчек)

2023-04-09 02:21 UTC, RickMortey commented on M.cpp
> +        int class_one = sort_counter = 0;
Новая инициализация на новой строке.

2023-04-09 02:21 UTC, RickMortey commented on M.cpp
> +            int k = (p[i]-d+n)%n;
Форматируй код. Между операциями должно быть по пробелу. Хоткей в Clion Ctrl+Alt+L вроде.

2023-04-09 02:21 UTC, RickMortey commented on I.cpp
> +}
Не забудь, что хэширование и поиск палиндорма -- разные сущности, разнеси в разные классы.

2023-05-10 12:00 UTC, RickMortey commented
Привет, ну я не могу аппрувнуть mr пока не будет сделана I
(плюсы каждой задачи на отдельной ветке бтв)
В целом с A и M всё ок.
Ты собираешься делать I или по нулям?

2023-05-10 12:02 UTC, Gaussiandra commented
Давай предварительно по нулям. Если что, я зашлю ещё один mr10.05.2023, 15:00, "Timur Uttsal" ***@***.***>:
Привет, ну я не могу аппрувнуть mr пока не будет сделана I
(плюсы каждой задачи на отдельной ветке бтв)
В целом с A и M всё ок.
Ты собираешься делать I или по нулям?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
--  

2023-05-22 19:21 UTC, merged